config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations' }

  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      resources :tours, only: %i[index show create update destroy] do
        resources :photos, only: %i[index show create update destroy]
      end

      resources :tourbooks

      resources :users, only: %i[show] do
        collection do
          get 'current_account'
        end

        resources :tourbooks, only: %i[index]
      end

      post '/viewpoints', to: 'photos#set_viewpoints'
      get '/viewpoints', to: 'photos#get_viewpoints'
      get '/users', to: 'users#get_info'

      get '*unmatched_route', to: 'base#user_not_authorized', code: 401
    end
  end

  resources :users, only: %i[show] do
    post 'generate_new_token', to: 'users#generate_new_token'
    get 'tourbooks', to: 'tourbooks#user_tourbooks'

    resources :tours, only: %i[show]

    resources :tourbooks, except: %i[index] do
      member do
        post 'add_item', to: 'tourbooks#add_item'
        delete 'remove_item', to: 'tourbooks#remove_item'
      end
    end
  end

  resources :photos, only: %i[index show] do
    collection do
      get 'viewpoints'
    end
  end

  get '/search_tours', to: 'tours#search_tours'
  get '/sitemap.xml', to: 'application#sitemap'
  get '/robots.txt' => 'robots_txts#show'
  get '/about', to: 'home#about'
  get '/upload', to: 'home#upload'

  root to: 'home#index'

end

app/views/finder/_filter_form.html.erb
<%= form_tag(request.path, method: :get, class: 'index-search-form page-item-search clearfix') do %>
  <input type="hidden" id="tab" name="tab" value="<%= @tab %>">
  <div class="search-text clearfix">
    <div class="search-input mt-3">
      <%= text_field_tag 'search_text', @search_text, class: 'search-text-input with-img form-control',
                          placeholder: 'Search' %>
    </div>

    <div class="search_country mt-3">
      <%= select_tag 'query[country_id]',
                      options_from_collection_for_select(Country.all.order(name: :asc),
                                                        'id',
                                                        'name',
                                                        @query.try(:[], :country_id) ),
                      class: 'select-country form-control',
                      include_blank: 'Country' %>
    </div>

    <div class="search_tour_type mt-3">
      <%= select_tag 'query[tour_type]',
                      options_for_select(tour_types_for_select, @query.try(:[], :tour_type)),
                      class: 'select-tour-type form-control',
                      include_blank: 'Tour type' %>
    </div>

    <div class="search_transport_type mt-3">
      <%= select_tag 'query[transport_type]',
                      options_for_select(transport_types_for_select, @query.try(:[], :transport_type)),
                      class: 'select-transport-type form-control',
                      include_blank: 'Transport type' %>
    </div>

    <button class="btn btn-primary mt-3">filter</button>

  </div>
<% end %>

app/views/finder/_toggle.html.erb
<div class="tours-books-toggle btn-group btn-group-toggle" data-toggle="buttons">
  <label class="btn btn-light <%= @tab == 'tours' ? 'active' : '' %>">
    <input type="radio" name="options" id="option-tour" autocomplete="off" checked> Tours
  </label>
  <label class="btn btn-light <%= @tab == 'tourbooks' ? 'active' : '' %>">
    <input type="radio" name="options" id="option-tourbooks" autocomplete="off"> Tourbooks
  </label>
</div>

app/views/finder/index.html.erb
<div class="row">
  <div class="col-lg-3">
    <h2 class="mt-5">Filters</h2>
    <%= render partial: 'finder/filter_form' %>
  </div>

  <div class="col-lg-9 home-content">
    <div class="row">
      <div class="col-md-9 col-sm-12 mt-8">
        <%= render partial: 'finder/toggle' %>
      </div>

      <% if user_signed_in? %>
        <div class="col-lg-3 col-sm-12 mt-4">
          <%= link_to 'New Tourbook', new_user_tourbook_path(current_user), class: 'btn btn-primary float-right new-tour-book-btn' %>
        </div>
      <% end %>
    </div>

    <div id="tours-content" style="<%= @tab == 'tours' ? '' : 'display: none;' %>">

      <div class="sort-wrapper">
        <%= render(SortComponent, collection_name: :tours, value: @sort.try(:[], :tours)) %>
      </div>

      <div class="row tours-container">
        <%= render partial: 'tours/tour', collection: @tours %>
      </div>
      <%= paginate @tours, param_name: :tour_pagina, :params => {:tab => "tours"} %>
    </div>

    <div id="tourbooks-content" style="<%= @tab == 'tourbooks' ? '' : 'display: none;' %>">

      <div class="sort-wrapper">
        <%= render(SortComponent, collection_name: :tourbooks, value: @sort.try(:[], :tourbooks)) %>
      </div>

      <div class="row">
        <div class="col-lg-12">
          <div class="row tours-container">
            <%= render partial: 'tourbooks/tourbooks_display' %>
          </div>
        </div>

      </div>
      <%= paginate @tourbooks, param_name: :tourbook_pagina, :params => {:tab => "tourbooks"} %>
    </div>

  </div>
</div>

<%= javascript_tag do %>
  $('.new-tour-book-btn').hide();

  $('#option-tour').change(function() {
    $('#tourbooks-content').hide();
    $('#tours-content').show();
    $('.new-tour-book-btn').hide();
    $('#tab').val('tours');
  });

  $('#option-tourbooks').change(function() {
    $('#tours-content').hide();
    $('#tourbooks-content').show();
    $('.new-tour-book-btn').show();
    $('#tab').val('tourbooks');
  });

<% end %>