config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations' }

  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      resources :tours, only: %i[index show create update destroy] do
        resources :photos, only: %i[index show create update destroy]
      end

      resources :tourbooks

      resources :users, only: %i[show] do
        collection do
          get 'current_account'
        end

        resources :tourbooks, only: %i[index]
      end

      post '/viewpoints', to: 'photos#set_viewpoints'
      get '/viewpoints', to: 'photos#get_viewpoints'
      get '/users', to: 'users#get_info'

      get '*unmatched_route', to: 'base#user_not_authorized', code: 401
    end
  end

  resources :users, only: %i[show] do
    post 'generate_new_token', to: 'users#generate_new_token'
    get 'tourbooks', to: 'tourbooks#user_tourbooks'

    resources :tours, only: %i[show]

    resources :tourbooks, except: %i[index] do
      member do
        post 'add_item', to: 'tourbooks#add_item'
        delete 'remove_item', to: 'tourbooks#remove_item'
      end
    end
  end

  resources :photos, only: %i[index show] do
    collection do
      get 'viewpoints'
    end
  end

  get '/search_tours', to: 'tours#search_tours'
  get '/sitemap.xml', to: 'application#sitemap'
  get '/robots.txt' => 'robots_txts#show'
  get '/about', to: 'home#about'
  get '/upload', to: 'home#upload'

  root to: 'home#index'

end

app/models/tour.rb
# frozen_string_literal: true
class Tour < ApplicationRecord

  include PgSearch::Model
  extend FriendlyId

  enum tour_type: Constants::TOUR_TYPES
  enum transport_type: Constants::TRANSPORT_TYPES

  belongs_to :user, :counter_cache => true

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :photos, dependent: :destroy
  has_many :countries, through: :photos
  has_many :tour_tourbooks, dependent: :destroy
  has_many :tourbooks, -> { distinct }, through: :tour_tourbooks, inverse_of: :tours

  # accepts_nested_attributes_for :photos

  validates :name, presence: true, uniqueness: { scope: :user_id }, length: { maximum: 70 }
  validates :description, length: { maximum: 16777215 }
  validates :tourer_tour_id, allow_blank: true, length: { maximum: 10 }
  validates :tourer_version, length: { maximum: 5 }
  validates :tour_type, presence: true
  validates :transport_type, presence: true

  validates_uniqueness_of :tourer_tour_id, :scope => :user_id, allow_blank: true

  validates_associated :tags
  validates_associated :countries

  validate :tags_amount
  validate :tags_length
  validate :tour_type_should_be_valid
  validate :transport_type_should_be_valid
  # validate :types_dependency

  friendly_id :name, :use => :scoped, :scope => :user

  pg_search_scope :search,
                  against: [
                      :name,
                      :description
                  ],
                  associated_against: {
                      tags: [:name],
                  },
                  :using => {
                      :tsearch => {:prefix => true}
                  }

  paginates_per Constants::ITEMS_PER_PAGE[:tours]

  def self.validates_uniqueness(*attribute_names)
    configuration = attribute_names.extract_options!
    validates_each(attribute_names) do |record, association_name, value|
      track_values = {}
      attribute_name = configuration[:attribute]
      value.map.with_index do |object, index|
        attribute_value = object.try(attribute_name)
        attribute_value = attribute_value.try(:downcase) if configuration[:case_sensitive] == false

        unless configuration[:allow_blank] == true && attribute_value.blank?
          if track_values[attribute_value].present?
            track_values[attribute_value].push({index: index, record: record})
          else
            track_values[attribute_value] = [{index: index, record: record}]
          end
        end

        track_values.each do |key, track_value|
          if track_value.count > 1
            track_value.each do |value|
              error_key = "#{association_name}[#{value[:index]}].#{attribute_name}"
              message = configuration[:message]
              value[:record].errors.add(error_key, message)
            end
          end
        end
      end
    end
  end

  # validates_uniqueness :photos, { attribute: :tourer_photo_id,
  #                                 case_sensitive: false,
  #                                 allow_blank: true,
  #                                 message: "Photo's tourer_photo_id should be unique per tour" }

  # Use default slug, but upper case and with underscores
  def normalize_friendly_id(string)
    super.gsub('-', '_')
  end

  def should_generate_new_friendly_id?
    name_changed? || slug.nil?
  end

  def countries=(codes_string)
    countries = []
    codes_string.split(', ').uniq.each do |code|
      countries << Country.find_or_initialize_by(code: code)
    end
    super countries
  end

  # for case if we will need to pass tags as a string and validate its length
  def tag_names=(names_string)
    self.tags = prepare_string(names_string).split(', ').map do |name|
      Tag.find_or_initialize_by(name: name.strip.downcase)
    end
  end

  def prepare_string(string)
    string.strip.chomp(',')
  end

  def tag_names
    self.tags.map(&:name).join(', ')
  end

  def tags_check(name)
    unless name.match(/\A[a-zA-Z0-9]*\z/)
      self.errors.add(:tags, "#{name} should not contain whitespaces or special characters") and return
    end
  end

  def tags_amount
    errors.add(:tags, "too much tags (maximum is #{Constants::TAGS_AMOUNT[:tour]} tags)") if tags.length > Constants::TAGS_AMOUNT[:tour]
  end

  def tags_length
    errors.add(:tags, "too much characters (maximum is #{Constants::TAGS_LENGTH[:tour]} tags)") if tag_names.length > Constants::TAGS_LENGTH[:tour]
  end

  # custom validation with message for enum :tour_type (as it raises ArgumentError in the case of wrong value)
  # standard validation doesn't help (validates_inclusion_of)
  def tour_type=(value)
    super value
    @tour_type_backup = nil
  rescue ArgumentError => exception
    error_message = 'is not a valid tour_type'
    if exception.message.include? error_message
      @tour_type_backup = value
      self[:tour_type] = nil
    else
      raise
    end
  end

  def tour_type_should_be_valid
    if @tour_type_backup
      error_message = "#{@tour_type_backup} is not a valid tour_type"
      errors.add(:tour_type, error_message)
    end
  end

  def transport_type=(value)
    super value
    @transport_type_backup = nil
  rescue ArgumentError => exception
    error_message = 'is not a valid transport_type'
    if exception.message.include? error_message
      @transport_type_backup = value
      self[:transport_type] = nil
    else
      raise
    end
  end

  def transport_type_should_be_valid
    if @transport_type_backup
      error_message = "#{@transport_type_backup} is not a valid transport_type"
      errors.add(:transport_type, error_message)
    end
  end

  def types_dependency
    if self[:tour_type].present? && self[:transport_type].present?
      error_message = "#{self[:tour_type]} and #{self[:transport_type]} mismatch"
      errors.add(:types_mismatch, error_message) unless Constants::DEPENDENCY_OF_TYPES[self[:tour_type]].include? self[:transport_type]
    end
  end
  #---------------------------------------------------------------------------------------------------------

end

app/controllers/api/v1/tours_controller.rb
# frozen_string_literal: true
module Api::V1
  class ToursController < BaseController

    before_action :set_tour, only: %i[show update destroy]
    before_action :set_user, only: %i[get_tours]

    # GET /api/v1/tours
    def index
      find_tours
      @tours = @tours.page(params[:page] ? params[:page].to_i : 1)
      tours_json = ActiveModelSerializers::SerializableResource.new(@tours).as_json
      tours_json['_metadata'] = pagination_meta(@tours)
      render json: tours_json, status: :ok
    end

    # GET /api/v1/tours/:id
    def show
      render json: @tour, status: :ok
    end

    # POST /api/v1/tours
    def create
      @tour = api_user.tours.build(tour_params)

      if @tour.save
        render json: @tour, status: :created
      else
        render json: {
            status: :unprocessable_entity,
            message: @tour.errors
        }, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /api/v1/tours/:id
    def update
      if tour_params[:name].present?
        render json: {
            status: :unprocessable_entity,
            message: 'you cannot update the name of a tour'
        }, status: :unprocessable_entity
        return
      end

      if api_user.tours.include?(@tour)
        begin
          if @tour.update(tour_params)
            render json: @tour.reload, status: :ok
          else
            render json: {
                status: :unprocessable_entity,
                message: @tour.errors
            }, status: :unprocessable_entity
          end
        rescue ArgumentError => e
          @tour.errors.add(:tour_type, e)
          render json: {
              status: :unprocessable_entity,
              message: @tour.errors
          }, status: :unprocessable_entity
        end
      else
        render json: {
            status: :unauthorized,
            message: 'You cannot update this tour'
        }, status: :unauthorized
      end
    end

    # DELETE /api/v1/tours/:id
    def destroy
      if api_user.tours.include?(@tour)
        @tour.destroy
        if @tour.errors.any?
          render json: {
              status: :unprocessable_entity,
              message: @tour.errors
          }, status: :unprocessable_entity
        else
          render json: {
                        "tour": {
                                  "id": @tour.id,
                                  "deleted_at": DateTime.now.rfc3339
                                }
                        }, status: :ok
        end
      else
        render json: {
            status: :unauthorized,
            message: 'You cannot delete this tour'
        }, status: :unauthorized
      end
    end

    # GET /api/v1/users/:user_id/tours
    def get_tours
      if api_user == @user
        render json: api_user.tours, status: :ok
      else
        render json: {
            status: :forbidden,
            message: 'You can get only your own tours'
        }, status: :forbidden
      end
    end

    private

    def set_tour
      @tour = Tour.find_by(id: params[:id])
    end

    def tour_params
      parameters = params.permit(*permitted_params)
      parameters[:tag_names] = parameters[:tags] if parameters[:tags]
      parameters[:tourer_tour_id] = parameters[:tourer][:tour_id] if parameters[:tourer]
      parameters[:tourer_version] = parameters[:tourer][:version] if parameters[:tourer]
      parameters.except(:tags, :tourer)
    end

    def set_user
      @user = User.find_by(id: params[:user_id])
    end

    def permitted_params
      [
          :name,
          :description,
          :tourer_tour_id,
          :tourer_version,
          :tour_type,
          :transport_type,
          :tags,
          tourer: [:tour_id, :version]
      ]
    end

    def list_tours
      @tours.map do |tour|
        {
            id: tour[:id],
            name: tour[:name],
            description: tour[:description],
            tour_type: tour[:tour_type],
            transport_type: tour[:transport_type],
            tourer_version: tour[:tourer_version],
            tourer_tour_id: tour[:tourer_tour_id],
            created_at: tour[:created_at],
            user_id: tour[:user_id]
        }
      end
    end

    def pagination_meta(object)
      {
        current_page: object.current_page,
        per_page: Constants::ITEMS_PER_PAGE[:tours],
        next_page: object.next_page,
        prev_page: object.prev_page,
        total_pages: object.total_pages,
        total_count: object.total_count
      }
    end

    def find_tours
      set_tours_search_params

      @tours = Tour.includes(:countries, :tags, :user)

      if @query.present?
        @tours = @tours.left_joins(:countries).where(countries: { code: @query[:countries] }).distinct if @query[:countries].present?
        @tours = @tours.left_joins(:tags).where(tags: { name: @query[:tags] }) if @query[:tags].present?
        @tours = @tours.where(id: @query[:ids]) if @query[:ids].present?
        @tours = @tours.where(user_id: @query[:user_ids]) if @query[:user_ids].present?

        if @query[:tour_types].present?
          tour_types = []
          @query[:tour_types].each do |t|
            tour_types << Constants::TOUR_TYPES[t.to_sym] if Constants::TOUR_TYPES.has_key?(t.to_sym)
          end
          @tours = @tours.where(tour_type: tour_types)
        end

        if @query[:transport_types].present?
          transport_types = []
          @query[:transport_types].each do |t|
            transport_types << Constants::TRANSPORT_TYPES[t.to_sym] if Constants::TRANSPORT_TYPES.has_key?(t.to_sym)
          end
          @tours = @tours.where(transport_type: transport_types)
        end

        if @query[:sort_by].present?
          if @query[:sort_by] == 'name'
            @tours = @tours.reorder("tours.#{@query[:sort_by]} ASC")
          else
            @tours = @tours.reorder("tours.#{@query[:sort_by]} DESC")
          end
        end
      end

      @tours = @tours.order(updated_at: :desc)
    end

    def set_tours_search_params
      @query = tour_search_params
    end

    def tour_search_params
      params.permit(:sort_by, ids: [], tags: [], countries: [], user_ids: [], tour_types: [], transport_types: [])
    end

  end

end

app/controllers/tours_controller.rb
# frozen_string_literal: true
class ToursController < ApplicationController
  include MetaTagsHelper

  before_action :set_tour, only: %i[show]

  def show
    set_sort_params
    @photos = @tour.photos
    @tourbooks = @tour.tourbooks

    if @sort.present?
      if @sort[:photos] == 'taken_at'
        @photos = @photos.order(taken_at: :desc)
      elsif @sort[:photos] == 'filename'
        @photos = @photos.order(filename: :asc)
      end

      @tourbooks = @tourbooks.order(name: :desc) if @sort[:tourbooks] == 'name'
      @tourbooks = @tourbooks.order('tourbooks.tours_count DESC') if @sort[:tourbooks] == 'tours_count'
    end
    @photos = @photos.order('substring(favoritable_score from 15)::integer ASC')
    @tourbooks = @tourbooks.order(created_at: :desc)

    @photos = @photos.page(params[:photo_pagina]).per(Constants::WEB_ITEMS_PER_PAGE[:tours])
    @tourbooks = @tourbooks.page(params[:tourbook_pagina]).per(Constants::WEB_ITEMS_PER_PAGE[:tourbooks])

    tour_og_meta_tag(@tour)
  end

  private

    def set_tour
      @tour = Tour.includes(:countries).friendly.find(params[:id])
    end

    def set_tours_search_params
      @search_text = tour_search_params[:search_text]
      @query = tour_search_params[:query]
    end

    def tour_search_params
      params.permit(:search_text, query: [:country_id, :tour_type])
    end

  def set_sort_params
    @sort = sort_params[:sort]
  end

  def sort_params
    params.permit(sort: [:photos, :tourbooks])
  end
end

app/helpers/tours_helper.rb
# frozen_string_literal: true
module ToursHelper

  def countries_for_select
    Country.all.map {|country| [country.name, country.id]}
  end

  def tour_types_for_select
    Tour.tour_types.map {|k , v| [k, v] }
  end

  def transport_types_for_select
    Tour.transport_types.map {|k , v| [k, v] }
  end

  def tour_countries(countries)
    countries.uniq { |c| c.id }
  end

end

app/views/tours/_create_tourbook.html.erb
<div class="modal fade" id="createTourbookModal" tabindex="-1" role="dialog" aria-labelledby="createTourBookModalCenter" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <%= form_with(url: user_tourbooks_path, scope: 'tourbook') do |f| %>

        <%= hidden_field_tag 'item_id', @tour.id %>

        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Create new Tourbook</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="form-errors">
            <%= form_errors_for f.object %>
          </div>
          <div class="form-group">
            <label for="create_tourbook_name" class="col-form-label">Name</label>
            <input type="text" class="form-control" id="create_tourbook_name" name="tourbook[name]">
          </div>
          <div class="form-group">
            <label for="create_tourbook_description" class="col-form-label">Description</label>
            <textarea class="form-control" id="create_tourbook_description" name="tourbook[description]"></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-danger">Create</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tours/_show_photo.html.erb
<div class="modal" tabindex="-1" role="dialog" id="showPhotoModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="imageContainer" ></div>
      </div>
    </div>
  </div>
</div>

app/views/tours/_tour.html.erb
<div id="tour-<%= tour.id %>" class="col-lg-4 col-md-6 mb-4 tour-item">
  <div class="card photo-card h-100">
    <span class="badge badge-primary badge-count" title="Added to Tourbook"><%= tour.tourbooks_count %></span>
    <% thumb_url = tour_thumb_url(tour) %>
    <% if thumb_url.present? %>
      <img class="card-img-top" src="<%= thumb_url %>" alt="">
    <% end %>
    <div class="card-body">
      <% if @tourbook.present? && policy(@tourbook).remove_item? %>
        <%= link_to remove_item_user_tourbook_path(tour.user, @tourbook, item_id: tour.id),
                    class: 'close delete_from_book',
                    title: 'delete tour from book',
                    data: {confirm: 'Are you sure?'},
                    method: :delete,
                    remote: true do %>
            <span aria-hidden="true">&times;</span>
        <% end %>
      <% end %>

      <h4 class="card-title">
        <%= link_to tour.name, user_tour_path(tour.user, tour) %>
      </h4>

      <p class="card-text"><%= truncate(tour.description, length: 120, separator: ' ') %></p>

      <div class="tags">
        <% tour.tags.each do |tag| %>
          <%= link_to "##{tag.name}", "?search_text=#{tag.name}", class: 'btn btn-info mb-1' %>
        <% end %>
      </div>

      <div class="tour_countries">
        <% tour_countries(tour.countries).each do |country| %>
          <%= link_to country.name, "?query[country_id]=#{country.id}", class: 'btn btn-warning mb-1' %>
        <% end %>
      </div>

      <% if tour.tour_type %>
        <div class="tour_type">
          <%= link_to tour.tour_type, "?query[tour_type]=#{Tour.tour_types[tour.tour_type]}", class: 'btn btn-primary mb-1' %>
        </div>
      <% end %>

      <% if tour.transport_type %>
        <div class="transport_type">
          <%= link_to tour.transport_type, "?query[transport_type]=#{Tour.transport_types[tour.transport_type]}", class: 'btn btn-secondary mb-1' %>
        </div>
      <% end %>

    </div>

    <div class="card-footer">
      <small class="text-muted">uploaded by: <%= link_to tour.user.try(:name), user_path(tour.user) %></small>
    </div>
  </div>

</div>

app/views/tours/index.html.erb
<div class="row">
  <div class="col-lg-3">
    <h2 class="mt-5">Filters</h2>
    <%= form_tag(tours_path, method: :get, class: 'index-search-form page-item-search clearfix') do %>
      <div class="search-text clearfix">
        <div class="search-input mt-3">
          <%= text_field_tag 'search_text', @search_text, class: 'search-text-input with-img form-control',
                             placeholder: 'Search for tours' %>
        </div>

        <div class="search_country mt-3">
          <%= select_tag 'query[country_id]',
                         options_from_collection_for_select(Country.all,
                                                            'id',
                                                            'name',
                                                            @query.try(:[], :country_id) ),
                         class: 'select-country form-control',
                         include_blank: 'Country' %>
        </div>

        <div class="search_tour_type mt-3">
          <%= select_tag 'query[tour_type]',
                         options_for_select(tour_types_for_select, @query.try(:[], :tour_type)),
                         class: 'select-tour-type form-control',
                         include_blank: 'Tour type' %>
        </div>

        <button class="btn btn-primary mt-3">filter</button>

      </div>
    <% end %>
  </div>

  <div class="col-lg-9 tours_list">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="my-4"><%= title 'List of Tours' %></h1>
        <% description app_description %>
      </div>

      <div class="col-lg-12">
        <div class="row tours-container">
          <%= render partial: 'tour', collection: @tours %>
        </div>
      </div>
    </div>

    <%= paginate @tours %>

  </div>
</div>

app/views/tours/search_tours.html.erb
<%= render partial: 'tour', collection: @tours %>

app/views/tours/show.html.erb
<% content_for :meta_title do %>
  <% @tour.name %>
<% end %>

<% content_for :meta_description do %>
  <% @tour.description %>
<% end %>

<% content_for :meta_image do %>
  <% @tour.photos.first.try(:streetview).try(:thumbnail_url) if @tour.photos.any? %>
<% end %>

<% if @tour.photos.any? %>
  <% provide :head_tags do %>
    <meta name='turbolinks-visit-control' content='reload'>
    <script>
        document.addEventListener("DOMContentLoaded", function(){
            var photos = <%= raw @tour.photos.try(:to_json) %>;
            initMap(photos);

            var chartData = <%= raw @tour.photos.group(:taken_at).maximum(:elevation_meters).try(:to_json) %>
            initElevationChart(chartData, photos);
        });
    </script>
  <% end %>
<% end %>

<div class="row">
  <div class="py-5 col-lg-12">
    <div class="card">
      <div class="card-header">
        <div class="row">
          <h1 class="<%= current_user ? 'col-lg-10' : 'col-lg-12' %> col-sm-12">
            <%= title "#{@tour.name} tour" %>
          </h1>

          <% description @tour.description %>

          <% if current_user %>
            <div class="col-lg-2 col-sm-12">
              <div class="float-right">

                <div class="btn-group mt-2">
                  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Add to Tourbook
                  </button>
                  <div id="tourBooksList" class="dropdown-menu">
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#createTourbookModal">Create new Tourbook</a>

                    <% if current_user.tourbooks.any? %>
                      <div class="dropdown-divider"></div>
                      <% current_user.tourbooks.each do |book| %>
                        <%= link_to book.name,
                                    add_item_user_tourbook_path(current_user, book, item_id: @tour.id),
                                    class: 'dropdown-item',
                                    remote: true,
                                    method: :post %>
                      <% end %>
                    <% end %>
                  </div>
                </div>

              </div>
            </div>
          <% end %>

        </div>
      </div>

      <div class="card-body">

        <h3 class="card-title"><%= @tour.name %></h3>

        <% if @tour.description.present? %>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-10">
              <p><%= @tour.description %></p>
            </div>
          </div>
        <% end %>

        <% if @tour.countries.any? %>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Tour location</label>
            <div class="col-sm-10">
              <% tour_countries(@tour.countries).each do |country| %>
                <%= link_to country.name, "?query[country_id]=#{country.id}", class: 'btn btn-warning' %>
              <% end %>
            </div>
          </div>
        <% end %>

        <% if @tour.tags.any? %>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Tags</label>
            <div class="col-sm-10">
              <% @tour.tags.each do |tag| %>
                <%= link_to tag.name, "?search_text=#{tag.name}", class: 'btn btn-info' %>
              <% end %>

            </div>
          </div>
        <% end %>

        <% if @tour.tour_type.present? %>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Tour type</label>
            <div class="col-sm-10">
              <%= link_to @tour.tour_type, "?query[tour_type]=#{@tour.tour_type}", class: 'btn btn-primary' %>
            </div>
          </div>
        <% end %>

        <% if @tour.transport_type.present? %>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Transport type</label>
            <div class="col-sm-10">
              <%= link_to @tour.transport_type, "?query[transport_type]=#{@tour.transport_type}", class: 'btn btn-secondary' %>
            </div>
          </div>
        <% end %>

        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Explorer Tour ID</label>
          <div class="col-sm-10">
            <%= @tour.id %>
          </div>
        </div>

        <% if @tour.tourer_tour_id.present? %>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Tourer Tour ID</label>
            <div class="col-sm-10">
              <%= @tour.tourer_tour_id %>
            </div>
          </div>
        <% end %>

        <h3 class="card-title">Tour sponsors</h3>

        <div class="row">
          <div class="col-sm-4">
            <div class="card text-white bg-success mb-3">
              <div class="card-header">Your name here</div>
              <div class="card-body">
                <p class="card-text">Is your small business nearby? Are you a local organisation? For a small donation you can be listed as a sponsor of this tour whilst supporting our work to protect the natural world. <a href="https://www.trekview.org/contact/" target="_blank">Contact us for more information</a>.</p>
              </div>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="card text-white bg-danger mb-3">
              <div class="card-header">Your name here</div>
              <div class="card-body">
                <p class="card-text">Is your small business nearby? Are you a local organisation? For a small donation you can be listed as a sponsor of this tour whilst supporting our work to protect the natural world. <a href="https://www.trekview.org/contact/" target="_blank">Contact us for more information</a>.</p>
              </div>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="card text-white bg-warning mb-3">
              <div class="card-header">Your name here</div>
              <div class="card-body">
                <p class="card-text">Is your small business nearby? Are you a local organisation? For a small donation you can be listed as a sponsor of this tour whilst supporting our work to protect the natural world. <a href="https://www.trekview.org/contact/" target="_blank">Contact us for more information</a>.</p>
              </div>
            </div>
          </div>

        </div>

        <% if @photos.any? %>

          <h3 class="card-title">Map</h3>

          <div id="map" class="mb-3"></div>

          <h3 class="card-title">Elevation Change</h3>

          <div class="mb-3">
            <div id="elevation-chart-container"></div>
          </div>

          <%= render partial: 'photos/photos_display', locals: { photos: @photos } %>
          <%= paginate @photos, param_name: :photo_pagina %>
        <% else %>

          <h3 class="card-title">Photos</h3>
          <p>None exist</p>

        <% end %>

        <h3 class="card-title">Tourbooks</h3>

        <% if @tourbooks.any? %>
          <div class="sort-wrapper">
            <%= render(SortComponent, collection_name: :tourbooks, value: @sort.try(:[], :tourbooks)) %>
          </div>

          <div class="row">
            <%= render partial: 'tourbooks/tourbooks_display' %>
            <%= paginate @tourbooks, param_name: :tourbook_pagina %>
          </div>
        <% else %>
          <p>None exist</p>
        <% end %>


      </div>

    </div>
  </div>
</div>


<%= render 'create_tourbook' %>

<%= render 'show_photo' %>