config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations' }

  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      resources :tours, only: %i[index show create update destroy] do
        resources :photos, only: %i[index show create update destroy]
      end

      resources :tourbooks

      resources :users, only: %i[show] do
        collection do
          get 'current_account'
        end

        resources :tourbooks, only: %i[index]
      end

      post '/viewpoints', to: 'photos#set_viewpoints'
      get '/viewpoints', to: 'photos#get_viewpoints'
      get '/users', to: 'users#get_info'

      get '*unmatched_route', to: 'base#user_not_authorized', code: 401
    end
  end

  resources :users, only: %i[show] do
    post 'generate_new_token', to: 'users#generate_new_token'
    get 'tourbooks', to: 'tourbooks#user_tourbooks'

    resources :tours, only: %i[show]

    resources :tourbooks, except: %i[index] do
      member do
        post 'add_item', to: 'tourbooks#add_item'
        delete 'remove_item', to: 'tourbooks#remove_item'
      end
    end
  end

  resources :photos, only: %i[index show] do
    collection do
      get 'viewpoints'
    end
  end

  get '/search_tours', to: 'tours#search_tours'
  get '/sitemap.xml', to: 'application#sitemap'
  get '/robots.txt' => 'robots_txts#show'
  get '/about', to: 'home#about'
  get '/upload', to: 'home#upload'

  root to: 'home#index'

end

app/views/layouts/_favicon.html.erb
<% %w(57 72 76 114 120 144 152 180).each do |size| %>
  <%= favicon_link_tag "apple-touch-icon-#{size}x#{size}.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<% end %>

<% %w(16 32).each do |size| %>
  <%= favicon_link_tag "favicon-#{size}x#{size}.png", rel: 'icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="py-4 bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md">
        <h5 class="text-white">About</h5>
        <p class="m-0 text-white">Unleash your inner explorer and travel the globe without leaving home. Take a journey to sites of cultural, historical, and geographic significance.</p>
        <br />
        <p class="m-0 text-white"><%= link_to 'Read more about how Explorer works here', '/about' %>.</p>
      </div>
      <div class="col-6 col-md">
        <h5 class="text-white">Resources</h5>
        <ul class="list-unstyled text-small text-white">
          <li><%= link_to 'Upload a Tour', '/upload' %></li>
          <li><a href="https://www.trekview.org/subscribe" target="_blank">Spotter a Trekker?</a></li>
          <li><a href="https://www.trekview.org/loan" target="_blank">Become a Trekker</a></li>
          <li><a href="https://gitlab.com/trekview/explorer/-/wikis/API-Documentation" target="_blank">Explorer API</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5 class="text-white">Find us on</h5>
        <ul class="list-unstyled text-small text-white">
          <li><a href="https://www.trekview.org/blog" target="_blank">Blog</a></li>
          <li><a href="https://trekview-slackin.herokuapp.com/" target="_blank">Community</a></li>
          <li><a href="https://www.facebook.com/trekview" target="_blank">Facebook</a></li>
          <li><a href="https://www.instagram.com/trekviewed/" target="_blank">Instagram</a></li>
          <li><a href="https://www.google.co.uk/maps/contrib/103906017035515964929/" target="_blank">Google</a></li>
          <li><a href="https://gitlab.com/trekview/" target="_blank">Gitlab</a></li>
        </ul>
      </div>
      <div class="col-12 col-md">
        <h5 class="text-white">License</h5>
        <p class="m-0 text-white">Help improve Explorer. This work is licensed under a <a href="https://gitlab.com/trekview/explorer/" target="_blank">GNU Affero General Public License v3.0</a>.</p>
        <br />
        <p class="m-0 text-white">&copy; <%= Time.current.year %> Trek View. <a href="https://www.trekview.org/about/" target="_blank">Read more about our work here</a>.</p>
      </div>
    </div>
  </div>
</footer>

<%= javascript_tag do %>
  <% if current_user.present? %>
    localStorage.setItem('api_token', "<%= current_user.api_token %>")
  <% else %>
    localStorage.removeItem('api_token')
  <% end %>

<% end %>

app/views/layouts/_google_analytics.html.erb
<% if Rails.env.production? %>
  <script async src="https://www.googletagmanager.com/gtag/js?id=<%= ENV['GOOGLE_ANALYTICS_KEY'] %>"></script>
  <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', '<%= ENV['GOOGLE_ANALYTICS_KEY'] %>');
  </script>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <%= link_to '/', class: 'navbar-brand explorer-logo' do %>
      <%= image_tag 'explorer-logo-rectangle.png', height: '40', width: '162' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to 'Top Viewpoints',
                      viewpoints_photos_path,
                      class: "nav-link #{current_class? photos_path }" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'My Profile',
                        user_path(current_user),
                        class: "nav-link #{current_class? user_path(current_user) }" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit my profile',
                        edit_user_registration_path,
                        class: "nav-link #{current_class? edit_user_registration_path }" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Log out',
                        destroy_user_session_path,
                        class: "nav-link #{current_class? destroy_user_session_path }",
                        method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign up',
                        new_user_registration_path,
                        class: "nav-link #{current_class? new_user_registration_path }" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Log in',
                        new_user_session_path,
                        class: "nav-link #{current_class? new_user_session_path }" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= display_meta_tags site: 'Explorer' %>

    <meta property="og:title" content="<%= meta_title %> | Explorer" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:description" content="<%= meta_description %>" />

    <%= include_gon(:init => true) %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'pannellum', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/google_analytics' %>
    <%= render 'layouts/favicon' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAPS_API_KEY']}" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'pannellum', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head_tags) %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container sticky-footer-wrapper d-flex flex-column">
      <div class="flash-messages">
        <%= render 'shared/flash_messages' %>
      </div>
      <div class="flex-fill">

        <%= yield %>

      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>